---
title: Cómo maniuplar mensajes de error
author: Elio Campitelli
date: '2021-07-13'
slug: wrapper-stop
categories:
  - R
keywords:
  - paquetes
  - programación
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>La función <code>stop()</code> permite terminar la ejecución de una función si hay algún problema mortal.</p>
<p>Por ejemplo, imaginemos este código que calcula la raziz cuadrada de un número pero sólo si el número de entrada es positivo.</p>
<pre class="r"><code>raiz_real &lt;- function(x) {
   if (x &lt; 0) {
      stop(&quot;&#39;x&#39; no puede ser negativo.&quot;)   
   } 
   sqrt(x)
}</code></pre>
<pre class="r"><code>raiz_real(2)</code></pre>
<pre><code>## [1] 1.414214</code></pre>
<pre class="r"><code>raiz_real(-2)</code></pre>
<pre><code>## Error in raiz_real(-2): &#39;x&#39; no puede ser negativo.</code></pre>
<p>Si x es negativo, la función tira un error.
Ahora imaginemos que esta función es parte de un paquete y le autor quiere que todos los mensajes de error estén siempre en mayúscula.
Y en vez de asegurarse de escribir todo en mayúscula prefiere usar la función <code>toupper()</code>:</p>
<pre class="r"><code>toupper(&quot;minúscula&quot;)</code></pre>
<pre><code>## [1] &quot;MINÚSCULA&quot;</code></pre>
<p>Entonces decide escribir la función <code>STOP()</code> que es una versión gritona de <code>stop()</code></p>
<pre class="r"><code>STOP &lt;- function(mensaje) {
   stop(toupper(mensaje))
}</code></pre>
<p>Y ahora redefine la función <code>RAIZ_REAL()</code> para usar esa función</p>
<pre class="r"><code>RAIZ_REAL &lt;- function(x) {
   if (x &lt; 0) {
      STOP(&quot;&#39;x&#39; no puede ser negativo.&quot;)   
   } 
   sqrt(x)
}</code></pre>
<pre class="r"><code>RAIZ_REAL(2)</code></pre>
<pre><code>## [1] 1.414214</code></pre>
<pre class="r"><code>RAIZ_REAL(-2)</code></pre>
<pre><code>## Error in STOP(&quot;&#39;x&#39; no puede ser negativo.&quot;): &#39;X&#39; NO PUEDE SER NEGATIVO.</code></pre>
<p>Parece que anda bien, pero hay un problema.
Antes, el error saltaba dentro de <code>raiz_real()</code>, por lo que el mensaje de error daba una pista de dónde estaba el fallo (<code>Error in raiz_real(-2) :...</code>).
Con este nuevo setup, como el error técnicamente ocurre dentro de <code>STOP()</code>, el mensaje de error pierde utilidad.
Peor aún, confunde al usuario!</p>
<p>Una solución es directamente esconder la llamada:</p>
<pre class="r"><code>STOP &lt;- function(mensaje) {
   stop(toupper(mensaje), call. = FALSE)
}</code></pre>
<pre class="r"><code>RAIZ_REAL(-2)</code></pre>
<pre><code>## Error: &#39;X&#39; NO PUEDE SER NEGATIVO.</code></pre>
<p>Ahora el mensaje no es tan útil, pero tampoco es activamente confuso.</p>
<p>Estaría bueno poder de alguna manera capturar la llamada anterior para que sea parte del mensaje de error.
Es decir, hacer que la función <code>STOP()</code> “sepa” qué otra expresión la llamó y use eso como texto.
Y eso se puede hacer con la función <code>sys.call()</code>.</p>
<p>La función <code>sys.call()</code> captura el código que llamó a una función, pero tiene un argumento que permite ir “para atrás” en el árbol de expresiones.</p>
<pre class="r"><code>funcion_exterior &lt;- function(x) {
   funcion_interior(x)
}

funcion_interior &lt;- function(x) {
   sys.call(x)
}</code></pre>
<p><code>funcion_exterior()</code> llama a <code>funcion_interior()</code> con el código <code>funcion_interior(x)</code>.
Como <code>x</code> es 0, <code>funcion_interior()</code> ejecuta <code>sys.call(0)</code>, que devuelve la última llamada, que es <code>funcion_interior(x).</code></p>
<pre class="r"><code>funcion_exterior(0)</code></pre>
<pre><code>## funcion_interior(x)</code></pre>
<p>Pero con el argumento <code>x</code> igual a -1, <code>funcion_interior()</code> ejecuta <code>sys.call(-1)</code>, que devuelve la penúltima llamada: <code>funcion_exterior(-1).</code></p>
<pre class="r"><code>funcion_exterior(-1)</code></pre>
<pre><code>## funcion_exterior(-1)</code></pre>
<p>El otro elemento es la función <code>simpleError()</code>, que sirve para generar un objeto de error que luego es interpretado correctamente por <code>stop()</code>.</p>
<pre class="r"><code>mensaje &lt;- &quot;esto es un error&quot;
error &lt;- simpleError(toupper(mensaje))
stop(error)</code></pre>
<pre><code>## Error: ESTO ES UN ERROR</code></pre>
<p>Juntando ambas piezas, queda:</p>
<pre class="r"><code>STOP &lt;- function(mensaje) {
   error &lt;- simpleError(toupper(mensaje), call = sys.call(-1))
   stop(error)
}</code></pre>
<p>Y ahora <code>RAIZ_REAL()</code> escupe un error tan útil como gritón</p>
<pre class="r"><code>RAIZ_REAL(-2)</code></pre>
<pre><code>## Error in RAIZ_REAL(-2): &#39;X&#39; NO PUEDE SER NEGATIVO.</code></pre>
